"""
Persistence repositories — flat re-export of all abstract interfaces and implementations,
plus the make_repositories() factory.
"""

from __future__ import annotations

from cloudtwin.persistence.repositories.aws import (
    InMemoryS3BucketRepository,
    InMemoryS3ObjectRepository,
    InMemorySesIdentityRepository,
    InMemorySesMessageRepository,
    InMemorySnsMessageRepository,
    InMemorySnsSubscriptionRepository,
    InMemorySnsTopicRepository,
    InMemorySqsMessageRepository,
    InMemorySqsQueueRepository,
    S3BucketRepository,
    S3ObjectRepository,
    SesIdentityRepository,
    SesMessageRepository,
    SnsMessageRepository,
    SnsSubscriptionRepository,
    SnsTopicRepository,
    SqliteS3BucketRepository,
    SqliteS3ObjectRepository,
    SqliteSesIdentityRepository,
    SqliteSesMessageRepository,
    SqliteSnsMessageRepository,
    SqliteSnsSubscriptionRepository,
    SqliteSnsTopicRepository,
    SqliteSqsMessageRepository,
    SqliteSqsQueueRepository,
    SqsMessageRepository,
    SqsQueueRepository,
    # Secrets Manager
    SecretRepository,
    SecretVersionRepository,
    SqliteSecretRepository,
    SqliteSecretVersionRepository,
    InMemorySecretRepository,
    InMemorySecretVersionRepository,
    # DynamoDB
    DynamoTableRepository,
    DynamoItemRepository,
    SqliteDynamoTableRepository,
    SqliteDynamoItemRepository,
    InMemoryDynamoTableRepository,
    InMemoryDynamoItemRepository,
    # Lambda
    LambdaFunctionRepository,
    LambdaInvocationRepository,
    SqliteLambdaFunctionRepository,
    SqliteLambdaInvocationRepository,
    InMemoryLambdaFunctionRepository,
    InMemoryLambdaInvocationRepository,
)
from cloudtwin.persistence.repositories.azure import (
    AsbMessageRepository,
    AsbQueueRepository,
    AsbSubscriptionRepository,
    AsbTopicRepository,
    AzureBlobRepository,
    AzureContainerRepository,
    InMemoryAsbMessageRepository,
    InMemoryAsbQueueRepository,
    InMemoryAsbSubscriptionRepository,
    InMemoryAsbTopicRepository,
    InMemoryAzureBlobRepository,
    InMemoryAzureContainerRepository,
    SqliteAsbMessageRepository,
    SqliteAsbQueueRepository,
    SqliteAsbSubscriptionRepository,
    SqliteAsbTopicRepository,
    SqliteAzureBlobRepository,
    SqliteAzureContainerRepository,
    # Queue Storage
    AzureStorageQueueRepository,
    AzureQueueMessageRepository,
    SqliteAzureStorageQueueRepository,
    SqliteAzureQueueMessageRepository,
    InMemoryAzureStorageQueueRepository,
    InMemoryAzureQueueMessageRepository,
    # Key Vault
    KeyVaultSecretRepository,
    SqliteKeyVaultSecretRepository,
    InMemoryKeyVaultSecretRepository,
    # Event Grid
    EventGridTopicRepository,
    EventGridEventRepository,
    SqliteEventGridTopicRepository,
    SqliteEventGridEventRepository,
    InMemoryEventGridTopicRepository,
    InMemoryEventGridEventRepository,
    # Functions
    AzureFunctionRepository,
    AzureFunctionInvocationRepository,
    SqliteAzureFunctionRepository,
    SqliteAzureFunctionInvocationRepository,
    InMemoryAzureFunctionRepository,
    InMemoryAzureFunctionInvocationRepository,
)
from cloudtwin.persistence.repositories.common import (
    EventRepository,
    InMemoryEventRepository,
    SqliteEventRepository,
)
from cloudtwin.persistence.repositories.gcp import (
    GcsBucketRepository,
    GcsObjectRepository,
    InMemoryGcsBucketRepository,
    InMemoryGcsObjectRepository,
    InMemoryPubsubAckableRepository,
    InMemoryPubsubMessageRepository,
    InMemoryPubsubSubscriptionRepository,
    InMemoryPubsubTopicRepository,
    PubsubAckableRepository,
    PubsubMessageRepository,
    PubsubSubscriptionRepository,
    PubsubTopicRepository,
    SqliteGcsBucketRepository,
    SqliteGcsObjectRepository,
    SqlitePubsubAckableRepository,
    SqlitePubsubMessageRepository,
    SqlitePubsubSubscriptionRepository,
    SqlitePubsubTopicRepository,
    # Firestore
    FirestoreDocumentRepository,
    InMemoryFirestoreDocumentRepository,
    SqliteFirestoreDocumentRepository,
    # Cloud Tasks
    CloudTasksQueueRepository,
    CloudTaskRepository,
    SqliteCloudTasksQueueRepository,
    SqliteCloudTaskRepository,
    InMemoryCloudTasksQueueRepository,
    InMemoryCloudTaskRepository,
    # Secret Manager
    GcpSecretRepository,
    GcpSecretVersionRepository,
    SqliteGcpSecretRepository,
    SqliteGcpSecretVersionRepository,
    InMemoryGcpSecretRepository,
    InMemoryGcpSecretVersionRepository,
    # Cloud Functions
    CloudFunctionRepository,
    CloudFunctionInvocationRepository,
    SqliteCloudFunctionRepository,
    SqliteCloudFunctionInvocationRepository,
    InMemoryCloudFunctionRepository,
    InMemoryCloudFunctionInvocationRepository,
)

__all__ = [
    # AWS
    "SesIdentityRepository", "SesMessageRepository",
    "S3BucketRepository", "S3ObjectRepository",
    "SnsTopicRepository", "SnsSubscriptionRepository", "SnsMessageRepository",
    "SqsQueueRepository", "SqsMessageRepository",
    "SqliteSesIdentityRepository", "SqliteSesMessageRepository",
    "SqliteS3BucketRepository", "SqliteS3ObjectRepository",
    "SqliteSnsTopicRepository", "SqliteSnsSubscriptionRepository", "SqliteSnsMessageRepository",
    "SqliteSqsQueueRepository", "SqliteSqsMessageRepository",
    "InMemorySesIdentityRepository", "InMemorySesMessageRepository",
    "InMemoryS3BucketRepository", "InMemoryS3ObjectRepository",
    "InMemorySnsTopicRepository", "InMemorySnsSubscriptionRepository", "InMemorySnsMessageRepository",
    "InMemorySqsQueueRepository", "InMemorySqsMessageRepository",
    "SecretRepository", "SecretVersionRepository",
    "SqliteSecretRepository", "SqliteSecretVersionRepository",
    "InMemorySecretRepository", "InMemorySecretVersionRepository",
    "DynamoTableRepository", "DynamoItemRepository",
    "SqliteDynamoTableRepository", "SqliteDynamoItemRepository",
    "InMemoryDynamoTableRepository", "InMemoryDynamoItemRepository",
    "LambdaFunctionRepository", "LambdaInvocationRepository",
    "SqliteLambdaFunctionRepository", "SqliteLambdaInvocationRepository",
    "InMemoryLambdaFunctionRepository", "InMemoryLambdaInvocationRepository",
    # Azure
    "AzureContainerRepository", "AzureBlobRepository",
    "AsbQueueRepository", "AsbTopicRepository", "AsbSubscriptionRepository", "AsbMessageRepository",
    "SqliteAzureContainerRepository", "SqliteAzureBlobRepository",
    "SqliteAsbQueueRepository", "SqliteAsbTopicRepository",
    "SqliteAsbSubscriptionRepository", "SqliteAsbMessageRepository",
    "InMemoryAzureContainerRepository", "InMemoryAzureBlobRepository",
    "InMemoryAsbQueueRepository", "InMemoryAsbTopicRepository",
    "InMemoryAsbSubscriptionRepository", "InMemoryAsbMessageRepository",
    "AzureStorageQueueRepository", "AzureQueueMessageRepository",
    "SqliteAzureStorageQueueRepository", "SqliteAzureQueueMessageRepository",
    "InMemoryAzureStorageQueueRepository", "InMemoryAzureQueueMessageRepository",
    "KeyVaultSecretRepository", "SqliteKeyVaultSecretRepository", "InMemoryKeyVaultSecretRepository",
    "EventGridTopicRepository", "EventGridEventRepository",
    "SqliteEventGridTopicRepository", "SqliteEventGridEventRepository",
    "InMemoryEventGridTopicRepository", "InMemoryEventGridEventRepository",
    "AzureFunctionRepository", "AzureFunctionInvocationRepository",
    "SqliteAzureFunctionRepository", "SqliteAzureFunctionInvocationRepository",
    "InMemoryAzureFunctionRepository", "InMemoryAzureFunctionInvocationRepository",
    # GCP
    "GcsBucketRepository", "GcsObjectRepository",
    "PubsubTopicRepository", "PubsubSubscriptionRepository",
    "PubsubMessageRepository", "PubsubAckableRepository",
    "SqliteGcsBucketRepository", "SqliteGcsObjectRepository",
    "SqlitePubsubTopicRepository", "SqlitePubsubSubscriptionRepository",
    "SqlitePubsubMessageRepository", "SqlitePubsubAckableRepository",
    "InMemoryGcsBucketRepository", "InMemoryGcsObjectRepository",
    "InMemoryPubsubTopicRepository", "InMemoryPubsubSubscriptionRepository",
    "InMemoryPubsubMessageRepository", "InMemoryPubsubAckableRepository",
    "FirestoreDocumentRepository",
    "SqliteFirestoreDocumentRepository",
    "InMemoryFirestoreDocumentRepository",
    "CloudTasksQueueRepository", "CloudTaskRepository",
    "SqliteCloudTasksQueueRepository", "SqliteCloudTaskRepository",
    "InMemoryCloudTasksQueueRepository", "InMemoryCloudTaskRepository",
    "GcpSecretRepository", "GcpSecretVersionRepository",
    "SqliteGcpSecretRepository", "SqliteGcpSecretVersionRepository",
    "InMemoryGcpSecretRepository", "InMemoryGcpSecretVersionRepository",
    "CloudFunctionRepository", "CloudFunctionInvocationRepository",
    "SqliteCloudFunctionRepository", "SqliteCloudFunctionInvocationRepository",
    "InMemoryCloudFunctionRepository", "InMemoryCloudFunctionInvocationRepository",
    # Common
    "EventRepository", "SqliteEventRepository", "InMemoryEventRepository",
    # Factory
    "make_repositories",
]


def make_repositories(db, mode: str = "sqlite") -> dict:
    """Return a dict of all repository instances for the selected storage mode."""
    if mode == "memory":
        return {
            # AWS
            "ses_identity": InMemorySesIdentityRepository(),
            "ses_message": InMemorySesMessageRepository(),
            "s3_bucket": InMemoryS3BucketRepository(),
            "s3_object": InMemoryS3ObjectRepository(),
            "sns_topic": InMemorySnsTopicRepository(),
            "sns_subscription": InMemorySnsSubscriptionRepository(),
            "sns_message": InMemorySnsMessageRepository(),
            "sqs_queue": InMemorySqsQueueRepository(),
            "sqs_message": InMemorySqsMessageRepository(),
            "sm_secret": InMemorySecretRepository(),
            "sm_secret_version": InMemorySecretVersionRepository(),
            "dynamo_table": InMemoryDynamoTableRepository(),
            "dynamo_item": InMemoryDynamoItemRepository(),
            "lambda_function": InMemoryLambdaFunctionRepository(),
            "lambda_invocation": InMemoryLambdaInvocationRepository(),
            # Azure
            "azure_container": InMemoryAzureContainerRepository(),
            "azure_blob": InMemoryAzureBlobRepository(),
            "asb_queue": InMemoryAsbQueueRepository(),
            "asb_topic": InMemoryAsbTopicRepository(),
            "asb_subscription": InMemoryAsbSubscriptionRepository(),
            "asb_message": InMemoryAsbMessageRepository(),
            "azure_storage_queue": InMemoryAzureStorageQueueRepository(),
            "azure_queue_message": InMemoryAzureQueueMessageRepository(),
            "kv_secret": InMemoryKeyVaultSecretRepository(),
            "eg_topic": InMemoryEventGridTopicRepository(),
            "eg_event": InMemoryEventGridEventRepository(),
            "azure_function": InMemoryAzureFunctionRepository(),
            "azure_function_invocation": InMemoryAzureFunctionInvocationRepository(),
            # GCP
            "gcs_bucket": InMemoryGcsBucketRepository(),
            "gcs_object": InMemoryGcsObjectRepository(),
            "pubsub_topic": InMemoryPubsubTopicRepository(),
            "pubsub_subscription": InMemoryPubsubSubscriptionRepository(),
            "pubsub_message": InMemoryPubsubMessageRepository(),
            "pubsub_ackable": InMemoryPubsubAckableRepository(),
            "firestore_document": InMemoryFirestoreDocumentRepository(),
            "ct_queue": InMemoryCloudTasksQueueRepository(),
            "ct_task": InMemoryCloudTaskRepository(),
            "gcp_secret": InMemoryGcpSecretRepository(),
            "gcp_secret_version": InMemoryGcpSecretVersionRepository(),
            "gcp_function": InMemoryCloudFunctionRepository(),
            "gcp_function_invocation": InMemoryCloudFunctionInvocationRepository(),
            # Common
            "event": InMemoryEventRepository(),
        }
    # SQLite mode
    return {
        # AWS
        "ses_identity": SqliteSesIdentityRepository(db),
        "ses_message": SqliteSesMessageRepository(db),
        "s3_bucket": SqliteS3BucketRepository(db),
        "s3_object": SqliteS3ObjectRepository(db),
        "sns_topic": SqliteSnsTopicRepository(db),
        "sns_subscription": SqliteSnsSubscriptionRepository(db),
        "sns_message": SqliteSnsMessageRepository(db),
        "sqs_queue": SqliteSqsQueueRepository(db),
        "sqs_message": SqliteSqsMessageRepository(db),
        "sm_secret": SqliteSecretRepository(db),
        "sm_secret_version": SqliteSecretVersionRepository(db),
        "dynamo_table": SqliteDynamoTableRepository(db),
        "dynamo_item": SqliteDynamoItemRepository(db),
        "lambda_function": SqliteLambdaFunctionRepository(db),
        "lambda_invocation": SqliteLambdaInvocationRepository(db),
        # Azure
        "azure_container": SqliteAzureContainerRepository(db),
        "azure_blob": SqliteAzureBlobRepository(db),
        "asb_queue": SqliteAsbQueueRepository(db),
        "asb_topic": SqliteAsbTopicRepository(db),
        "asb_subscription": SqliteAsbSubscriptionRepository(db),
        "asb_message": SqliteAsbMessageRepository(db),
        "azure_storage_queue": SqliteAzureStorageQueueRepository(db),
        "azure_queue_message": SqliteAzureQueueMessageRepository(db),
        "kv_secret": SqliteKeyVaultSecretRepository(db),
        "eg_topic": SqliteEventGridTopicRepository(db),
        "eg_event": SqliteEventGridEventRepository(db),
        "azure_function": SqliteAzureFunctionRepository(db),
        "azure_function_invocation": SqliteAzureFunctionInvocationRepository(db),
        # GCP
        "gcs_bucket": SqliteGcsBucketRepository(db),
        "gcs_object": SqliteGcsObjectRepository(db),
        "pubsub_topic": SqlitePubsubTopicRepository(db),
        "pubsub_subscription": SqlitePubsubSubscriptionRepository(db),
        "pubsub_message": SqlitePubsubMessageRepository(db),
        "pubsub_ackable": SqlitePubsubAckableRepository(db),
        "firestore_document": SqliteFirestoreDocumentRepository(db),
        "ct_queue": SqliteCloudTasksQueueRepository(db),
        "ct_task": SqliteCloudTaskRepository(db),
        "gcp_secret": SqliteGcpSecretRepository(db),
        "gcp_secret_version": SqliteGcpSecretVersionRepository(db),
        "gcp_function": SqliteCloudFunctionRepository(db),
        "gcp_function_invocation": SqliteCloudFunctionInvocationRepository(db),
        # Common
        "event": SqliteEventRepository(db),
    }
