"""
Persistence repositories — flat re-export of all abstract interfaces and implementations,
plus the make_repositories() factory.
"""

from __future__ import annotations

from cloudtwin.persistence.repositories.aws import (  # Secrets Manager; DynamoDB; Lambda
    DynamoItemRepository,
    DynamoTableRepository,
    LambdaFunctionRepository,
    LambdaInvocationRepository,
    S3BucketRepository,
    S3ObjectRepository,
    SecretRepository,
    SecretVersionRepository,
    SesIdentityRepository,
    SesMessageRepository,
    SnsMessageRepository,
    SnsSubscriptionRepository,
    SnsTopicRepository,
    SqliteDynamoItemRepository,
    SqliteDynamoTableRepository,
    SqliteLambdaFunctionRepository,
    SqliteLambdaInvocationRepository,
    SqliteS3BucketRepository,
    SqliteS3ObjectRepository,
    SqliteSecretRepository,
    SqliteSecretVersionRepository,
    SqliteSesIdentityRepository,
    SqliteSesMessageRepository,
    SqliteSnsMessageRepository,
    SqliteSnsSubscriptionRepository,
    SqliteSnsTopicRepository,
    SqliteSqsMessageRepository,
    SqliteSqsQueueRepository,
    SqsMessageRepository,
    SqsQueueRepository,
)
from cloudtwin.persistence.repositories.azure import (  # Queue Storage; Key Vault; Event Grid; Functions
    AsbMessageRepository,
    AsbQueueRepository,
    AsbSubscriptionRepository,
    AsbTopicRepository,
    AzureBlobRepository,
    AzureContainerRepository,
    AzureFunctionInvocationRepository,
    AzureFunctionRepository,
    AzureQueueMessageRepository,
    AzureStorageQueueRepository,
    EventGridEventRepository,
    EventGridTopicRepository,
    KeyVaultSecretRepository,
    SqliteAsbMessageRepository,
    SqliteAsbQueueRepository,
    SqliteAsbSubscriptionRepository,
    SqliteAsbTopicRepository,
    SqliteAzureBlobRepository,
    SqliteAzureContainerRepository,
    SqliteAzureFunctionInvocationRepository,
    SqliteAzureFunctionRepository,
    SqliteAzureQueueMessageRepository,
    SqliteAzureStorageQueueRepository,
    SqliteEventGridEventRepository,
    SqliteEventGridTopicRepository,
    SqliteKeyVaultSecretRepository,
)
from cloudtwin.persistence.repositories.common import (
    EventRepository,
    SqliteEventRepository,
)
from cloudtwin.persistence.repositories.gcp import (  # Firestore; Cloud Tasks; Secret Manager; Cloud Functions
    CloudFunctionInvocationRepository,
    CloudFunctionRepository,
    CloudTaskRepository,
    CloudTasksQueueRepository,
    FirestoreDocumentRepository,
    GcpSecretRepository,
    GcpSecretVersionRepository,
    GcsBucketRepository,
    GcsObjectRepository,
    PubsubAckableRepository,
    PubsubMessageRepository,
    PubsubSubscriptionRepository,
    PubsubTopicRepository,
    SqliteCloudFunctionInvocationRepository,
    SqliteCloudFunctionRepository,
    SqliteCloudTaskRepository,
    SqliteCloudTasksQueueRepository,
    SqliteFirestoreDocumentRepository,
    SqliteGcpSecretRepository,
    SqliteGcpSecretVersionRepository,
    SqliteGcsBucketRepository,
    SqliteGcsObjectRepository,
    SqlitePubsubAckableRepository,
    SqlitePubsubMessageRepository,
    SqlitePubsubSubscriptionRepository,
    SqlitePubsubTopicRepository,
)

__all__ = [
    # AWS
    "SesIdentityRepository",
    "SesMessageRepository",
    "S3BucketRepository",
    "S3ObjectRepository",
    "SnsTopicRepository",
    "SnsSubscriptionRepository",
    "SnsMessageRepository",
    "SqsQueueRepository",
    "SqsMessageRepository",
    "SqliteSesIdentityRepository",
    "SqliteSesMessageRepository",
    "SqliteS3BucketRepository",
    "SqliteS3ObjectRepository",
    "SqliteSnsTopicRepository",
    "SqliteSnsSubscriptionRepository",
    "SqliteSnsMessageRepository",
    "SqliteSqsQueueRepository",
    "SqliteSqsMessageRepository",
    "SecretRepository",
    "SecretVersionRepository",
    "SqliteSecretRepository",
    "SqliteSecretVersionRepository",
    "DynamoTableRepository",
    "DynamoItemRepository",
    "SqliteDynamoTableRepository",
    "SqliteDynamoItemRepository",
    "LambdaFunctionRepository",
    "LambdaInvocationRepository",
    "SqliteLambdaFunctionRepository",
    "SqliteLambdaInvocationRepository",
    # Azure
    "AzureContainerRepository",
    "AzureBlobRepository",
    "AsbQueueRepository",
    "AsbTopicRepository",
    "AsbSubscriptionRepository",
    "AsbMessageRepository",
    "SqliteAzureContainerRepository",
    "SqliteAzureBlobRepository",
    "SqliteAsbQueueRepository",
    "SqliteAsbTopicRepository",
    "SqliteAsbSubscriptionRepository",
    "SqliteAsbMessageRepository",
    "AzureStorageQueueRepository",
    "AzureQueueMessageRepository",
    "SqliteAzureStorageQueueRepository",
    "SqliteAzureQueueMessageRepository",
    "KeyVaultSecretRepository",
    "SqliteKeyVaultSecretRepository",
    "EventGridTopicRepository",
    "EventGridEventRepository",
    "SqliteEventGridTopicRepository",
    "SqliteEventGridEventRepository",
    "AzureFunctionRepository",
    "AzureFunctionInvocationRepository",
    "SqliteAzureFunctionRepository",
    "SqliteAzureFunctionInvocationRepository",
    # GCP
    "GcsBucketRepository",
    "GcsObjectRepository",
    "PubsubTopicRepository",
    "PubsubSubscriptionRepository",
    "PubsubMessageRepository",
    "PubsubAckableRepository",
    "SqliteGcsBucketRepository",
    "SqliteGcsObjectRepository",
    "SqlitePubsubTopicRepository",
    "SqlitePubsubSubscriptionRepository",
    "SqlitePubsubMessageRepository",
    "SqlitePubsubAckableRepository",
    "FirestoreDocumentRepository",
    "SqliteFirestoreDocumentRepository",
    "CloudTasksQueueRepository",
    "CloudTaskRepository",
    "SqliteCloudTasksQueueRepository",
    "SqliteCloudTaskRepository",
    "GcpSecretRepository",
    "GcpSecretVersionRepository",
    "SqliteGcpSecretRepository",
    "SqliteGcpSecretVersionRepository",
    "CloudFunctionRepository",
    "CloudFunctionInvocationRepository",
    "SqliteCloudFunctionRepository",
    "SqliteCloudFunctionInvocationRepository",
    # Common
    "EventRepository",
    "SqliteEventRepository",
    # Factory
    "make_repositories",
]


def make_repositories(db, mode: str = "sqlite") -> dict:
    """Return a dict of all repository instances backed by the given Database.

    Both storage modes use the same SQLite-backed implementations:
      - mode="sqlite"  → persistent SQLite file
      - mode="memory"  → SQLite :memory: connection (no file I/O)

    The Database class handles the connection details; repositories are
    unaware of whether the underlying connection is file-backed or in-memory.
    """
    return {
        # AWS
        "ses_identity": SqliteSesIdentityRepository(db),
        "ses_message": SqliteSesMessageRepository(db),
        "s3_bucket": SqliteS3BucketRepository(db),
        "s3_object": SqliteS3ObjectRepository(db),
        "sns_topic": SqliteSnsTopicRepository(db),
        "sns_subscription": SqliteSnsSubscriptionRepository(db),
        "sns_message": SqliteSnsMessageRepository(db),
        "sqs_queue": SqliteSqsQueueRepository(db),
        "sqs_message": SqliteSqsMessageRepository(db),
        "sm_secret": SqliteSecretRepository(db),
        "sm_secret_version": SqliteSecretVersionRepository(db),
        "dynamo_table": SqliteDynamoTableRepository(db),
        "dynamo_item": SqliteDynamoItemRepository(db),
        "lambda_function": SqliteLambdaFunctionRepository(db),
        "lambda_invocation": SqliteLambdaInvocationRepository(db),
        # Azure
        "azure_container": SqliteAzureContainerRepository(db),
        "azure_blob": SqliteAzureBlobRepository(db),
        "asb_queue": SqliteAsbQueueRepository(db),
        "asb_topic": SqliteAsbTopicRepository(db),
        "asb_subscription": SqliteAsbSubscriptionRepository(db),
        "asb_message": SqliteAsbMessageRepository(db),
        "azure_storage_queue": SqliteAzureStorageQueueRepository(db),
        "azure_queue_message": SqliteAzureQueueMessageRepository(db),
        "kv_secret": SqliteKeyVaultSecretRepository(db),
        "eg_topic": SqliteEventGridTopicRepository(db),
        "eg_event": SqliteEventGridEventRepository(db),
        "azure_function": SqliteAzureFunctionRepository(db),
        "azure_function_invocation": SqliteAzureFunctionInvocationRepository(db),
        # GCP
        "gcs_bucket": SqliteGcsBucketRepository(db),
        "gcs_object": SqliteGcsObjectRepository(db),
        "pubsub_topic": SqlitePubsubTopicRepository(db),
        "pubsub_subscription": SqlitePubsubSubscriptionRepository(db),
        "pubsub_message": SqlitePubsubMessageRepository(db),
        "pubsub_ackable": SqlitePubsubAckableRepository(db),
        "firestore_document": SqliteFirestoreDocumentRepository(db),
        "ct_queue": SqliteCloudTasksQueueRepository(db),
        "ct_task": SqliteCloudTaskRepository(db),
        "gcp_secret": SqliteGcpSecretRepository(db),
        "gcp_secret_version": SqliteGcpSecretVersionRepository(db),
        "gcp_function": SqliteCloudFunctionRepository(db),
        "gcp_function_invocation": SqliteCloudFunctionInvocationRepository(db),
        # Common
        "event": SqliteEventRepository(db),
    }
